In [2]:
!pip install --q anndata
!pip install --q scipy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 122.4/122.4 kB 1.2 MB/s eta 0:00:00

In [3]:
import numpy as np
import pandas as pd
import anndata as ad
from scipy.sparse import csr_matrix
print(ad.__version__)

0.10.7

In [4]:
counts = csr_matrix(np.random.poisson(1, size=(100, 2000)), dtype=np.float32)
adata = ad.AnnData(counts)
adata

AnnData object with n_obs × n_vars = 100 × 2000

In [10]:
adata.X

<100x2000 sparse matrix of type '<class 'numpy.float32'>'
	with 126638 stored elements in Compressed Sparse Row format>

In [11]:
adata.obs_names = [f"Cell_{i:d}" for i in range(adata.n_obs)]
adata.var_names = [f"Gene_{i:d}" for i in range(adata.n_vars)]
print(adata.obs_names[:15])
print(adata.var_names[:15])

Index(['Cell_0', 'Cell_1', 'Cell_2', 'Cell_3', 'Cell_4', 'Cell_5', 'Cell_6',
       'Cell_7', 'Cell_8', 'Cell_9', 'Cell_10', 'Cell_11', 'Cell_12',
       'Cell_13', 'Cell_14'],
      dtype='object')
Index(['Gene_0', 'Gene_1', 'Gene_2', 'Gene_3', 'Gene_4', 'Gene_5', 'Gene_6',
       'Gene_7', 'Gene_8', 'Gene_9', 'Gene_10', 'Gene_11', 'Gene_12',
       'Gene_13', 'Gene_14'],
      dtype='object')

In [14]:
adata[["Cell_1", "Cell_10"], ["Gene_5", "Gene_1900", "Gene_32"]]

View of AnnData object with n_obs × n_vars = 2 × 3

In [15]:
ct = np.random.choice(["B", "T", "Monocyte"], size=(adata.n_obs,))
adata.obs["cell_type"] = pd.Categorical(ct)  # Categoricals are preferred for efficiency
adata.obs

        cell_type
Cell_0   Monocyte
Cell_1   Monocyte
Cell_2          T
Cell_3   Monocyte
Cell_4          T
...           ...
Cell_95         B
Cell_96         B
Cell_97         B
Cell_98         B
Cell_99         B

[100 rows x 1 columns]

In [16]:
bdata = adata[adata.obs.cell_type == "B"]
bdata

View of AnnData object with n_obs × n_vars = 44 × 2000
    obs: 'cell_type'

In [17]:
adata.obsm["X_umap"] = np.random.normal(0, 1, size=(adata.n_obs, 2))
adata.varm["gene_stuff"] = np.random.normal(0, 1, size=(adata.n_vars, 5))
adata.obsm

AxisArrays with keys: X_umap

In [36]:
adata.layers["log_transformed"] = np.log1p(adata.X)
adata

AnnData object with n_obs × n_vars = 100 × 2000
    obs: 'cell_type'
    obsm: 'X_umap'
    varm: 'gene_stuff'
    layers: 'log_transformed'

In [42]:
bdata.to_df(layer="log_transformed")

,Gene_0,Gene_1,Gene_2,Gene_3,Gene_4,Gene_5,Gene_6,Gene_7,Gene_8,Gene_9,...,Gene_1990,Gene_1991,Gene_1992,Gene_1993,Gene_1994,Gene_1995,Gene_1996,Gene_1997,Gene_1998,Gene_1999
Cell_8,1.098612,0.000000,1.098612,0.693147,0.693147,0.693147,0.000000,1.098612,0.000000,0.000000,...,1.098612,0.693147,0.693147,0.693147,0.693147,1.386294,0.693147,0.693147,0.693147,0.000000
Cell_10,0.000000,0.693147,1.098612,1.098612,0.000000,1.098612,0.000000,0.000000,1.386294,1.609438,...,0.000000,0.000000,0.693147,1.098612,0.000000,0.693147,0.000000,0.000000,0.693147,0.000000
Cell_11,1.098612,0.693147,1.386294,0.000000,0.000000,0.000000,0.693147,0.693147,0.693147,0.693147,...,0.000000,0.000000,0.693147,0.000000,1.098612,1.098612,0.693147,0.000000,0.000000,0.693147
Cell_13,0.000000,0.693147,0.693147,0.693147,0.693147,1.098612,0.693147,0.693147,0.000000,0.693147,...,0.000000,0.693147,0.693147,0.693147,1.098612,0.693147,0.693147,0.000000,1.098612,0.000000
Cell_14,1.098612,0.000000,0.000000,0.000000,1.098612,0.000000,1.386294,0.000000,0.693147,1.386294,...,1.386294,0.000000,0.000000,0.000000,0.000000,1.098612,0.000000,0.693147,0.000000,0.000000
Cell_16,0.693147,0.000000,0.000000,0.693147,0.693147,0.693147,0.000000,0.693147,1.791759,1.098612,...,0.693147,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.693147,0.693147,0.000000
Cell_22,0.693147,1.098612,0.000000,0.693147,0.693147,0.693147,0.693147,0.693147,0.693147,0.693147,...,0.693147,0.000000,0.693147,0.000000,0.693147,0.693147,1.386294,0.693147,1.098612,0.693147
Cell_23,1.098612,0.000000,0.693147,1.098612,0.693147,1.098612,0.000000,0.000000,0.000000,0.693147,...,0.000000,1.386294,0.693147,0.693147,0.000000,0.693147,0.000000,1.098612,0.693147,1.386294
Cell_29,1.386294,1.098612,0.693147,0.000000,1.098612,1.098612,0.000000,0.693147,0.693147,0.000000,...,0.693147,0.000000,0.693147,1.098612,0.000000,1.386294,0.693147,0.693147,0.000000,1.098612
Cell_32,1.609438,1.098612,0.000000,0.693147,0.693147,0.693147,0.000000,0.000000,0.000000,0.000000,...,0.693147,0.000000,1.098612,0.693147,0.000000,0.000000,1.098612,1.098612,0.693147,1.098612
Cell_34,1.098612,0.000000,0.693147,1.098612,0.000000,0.000000,0.693147,0.000000,0.693147,0.000000,...,0.000000,1.609438,0.000000,0.693147,0.000000,0.000000,0.693147,0.693147,1.386294,0.000000
Cell_35,0.693147,0.693147,0.693147,0.693147,0.000000,0.000000,0.693147,0.693147,0.693147,0.693147,...,1.386294,0.000000,0.000000,1.098612,0.000000,0.000000,0.693147,0.693147,0.693147,0.000000
Cell_36,0.693147,0.693147,1.098612,0.693147,0.000000,1.098612,0.000000,0.000000,0.693147,0.000000,...,0.000000,0.693147,0.000000,0.693147,1.098612,0.000000,1.098612,0.000000,0.000000,0.693147
Cell_37,0.000000,0.693147,0.693147,0.693147,1.098612,0.693147,0.000000,0.693147,0.693147,0.693147,...,0.000000,1.386294,0.693147,1.098612,0.000000,0.693147,0.693147,0.693147,0.000000,1.098612
Cell_39,0.693147,0.693147,0.693147,0.693147,0.000000,1.098612,0.693147,0.693147,1.098612,0.000000,...,0.693147,0.000000,0.000000,1.098612,0.693147,0.000000,0.000000,1.098612,0.693147,1.098612
Cell_40,0.000000,0.000000,0.000000,1.386294,0.693147,1.098612,1.098612,0.693147,0.000000,0.000000,...,0.000000,0.000000,1.098612,1.098612,0.000000,0.000000,0.693147,1.098612,0.000000,1.386294
Cell_41,1.386294,1.098612,0.000000,1.098612,0.000000,0.000000,0.000000,0.000000,1.098612,0.000000,...,0.693147,0.000000,0.000000,0.693147,0.693147,1.098612,0.693147,0.000000,0.000000,0.693147
Cell_46,1.386294,0.693147,0.000000,0.000000,0.693147,1.098612,0.693147,0.693147,0.000000,0.693147,...,0.000000,1.098612,0.693147,1.609438,0.693147,1.098612,0.000000,1.098612,0.693147,1.386294
Cell_47,0.000000,0.693147,0.000000,0.000000,0.000000,1.098612,0.693147,0.693147,0.000000,0.693147,...,1.386294,0.693147,0.693147,0.000000,0.693147,0.000000,0.000000,0.000000,0.000000,0.000000
Cell_48,1.098612,0.693147,1.098612,0.693147,0.693147,1.098612,0.000000,0.693147,0.693147,0.000000,...,0.000000,0.000000,0.000000,1.098612,0.693147,1.098612,1.386294,0.693147,0.693147,0.693147
Cell_49,0.000000,1.098612,1.386294,0.000000,0.000000,1.098612,0.000000,0.693147,0.000000,0.000000,...,0.693147,0.000000,0.000000,0.693147,1.609438,0.693147,0.000000,0.000000,0.693147,0.000000
Cell_50,0.693147,0.000000,0.693147,0.000000,1.098612,0.000000,0.693147,0.693147,1.386294,0.693147,...,0.000000,0.693147,0.000000,0.693147,0.000000,0.693147,0.693147,1.098612,0.693147,1.386294
Cell_56,0.000000,0.693147,0.693147,1.386294,0.000000,1.386294,1.098612,0.693147,0.693147,1.098612,...,0.000000,0.693147,0.000000,1.098612,0.693147,0.693147,0.693147,0.000000,0.000000,1.098612
Cell_57,1.098612,1.386294,0.693147,0.000000,1.098612,1.386294,0.693147,1.098612,1.098612,0.693147,...,0.000000,0.000000,1.098612,0.000000,0.693147,0.000000,1.386294,0.000000,0.693147,0.693147
Cell_59,0.693147,0.693147,0.693147,0.000000,0.000000,0.693147,0.693147,0.000000,0.693147,0.000000,...,0.693147,1.098612,0.000000,0.693147,0.000000,0.000000,0.000000,0.000000,0.000000,1.098612
Cell_60,0.000000,0.000000,0.693147,1.098612,0.000000,1.098612,1.098612,0.000000,0.000000,1.098612,...,0.693147,0.693147,0.693147,0.000000,0.693147,0.693147,0.000000,0.693147,0.000000,0.000000
Cell_64,0.693147,1.609438,1.098612,1.098612,0.000000,0.000000,1.386294,0.693147,0.693147,0.693147,...,0.693147,1.098612,0.693147,1.386294,0.000000,0.693147,0.000000,0.000000,0.000000,1.386294
Cell_65,1.098612,0.000000,1.098612,0.000000,1.098612,0.000000,0.693147,0.693147,0.693147,0.693147,...,1.098612,0.693147,0.000000,0.693147,0.000000,1.386294,1.098612,0.693147,0.693147,0.000000
Cell_66,0.000000,0.693147,0.000000,0.693147,0.693147,1.098612,1.098612,0.000000,0.000000,0.693147,...,0.000000,0.000000,1.098612,1.791759,0.693147,0.000000,0.693147,0.000000,1.098612,0.693147
Cell_69,0.693147,0.693147,0.000000,0.000000,0.000000,0.693147,0.693147,0.000000,0.693147,0.693147,...,0.693147,1.098612,1.098612,0.693147,1.098612,0.693147,0.000000,0.000000,1.098612,0.693147
Cell_71,0.000000,0.000000,0.000000,0.693147,0.693147,0.693147,0.693147,0.693147,0.000000,1.098612,...,0.693147,0.693147,0.000000,0.000000,0.000000,0.693147,0.693147,0.000000,0.693147,0.000000
Cell_74,0.000000,0.693147,0.693147,0.000000,1.098612,0.693147,0.000000,0.000000,0.693147,0.693147,...,1.386294,0.000000,1.386294,0.693147,0.000000,0.000000,0.000000,0.000000,0.000000,0.693147
Cell_75,0.000000,0.000000,0.693147,0.000000,0.693147,0.000000,1.098612,0.693147,0.693147,0.000000,...,0.000000,0.693147,0.000000,0.693147,0.000000,0.000000,1.386294,0.000000,0.693147,1.098612
Cell_77,0.693147,1.609438,0.693147,0.000000,0.000000,1.098612,0.693147,0.693147,0.000000,0.693147,...,1.609438,0.693147,0.693147,1.098612,0.693147,0.000000,0.693147,0.693147,0.693147,0.693147
Cell_79,0.000000,1.098612,1.386294,1.098612,1.098612,1.609438,0.693147,0.693147,0.000000,1.098612,...,0.000000,0.693147,0.693147,0.693147,0.693147,0.693147,0.693147,0.000000,0.000000,0.693147
Cell_80,1.098612,0.693147,0.693147,0.000000,1.386294,0.000000,0.693147,1.098612,0.000000,0.693147,...,0.000000,0.000000,0.693147,0.000000,1.098612,1.098612,0.000000,0.000000,1.609438,1.098612
Cell_83,1.609438,1.098612,0.000000,0.000000,0.693147,0.000000,0.000000,0.693147,0.693147,0.693147,...,1.386294,1.386294,0.693147,0.000000,0.693147,0.000000,0.000000,0.000000,1.386294,1.098612
Cell_85,0.693147,0.693147,0.693147,1.386294,0.000000,0.000000,0.693147,1.098612,0.000000,0.000000,...,1.098612,1.098612,1.098612,1.098612,0.693147,0.693147,0.693147,0.693147,0.000000,1.098612
Cell_86,1.098612,0.000000,0.000000,1.098612,1.098612,1.609438,1.386294,0.693147,0.000000,0.693147,...,0.693147,0.693147,0.000000,0.693147,1.098612,0.693147,0.000000,0.693147,0.000000,0.000000
Cell_95,0.693147,0.000000,0.000000,0.693147,1.098612,0.000000,0.000000,0.693147,0.693147,0.693147,...,1.098612,0.693147,0.693147,1.098612,0.000000,1.098612,1.098612,0.000000,0.000000,0.000000
Cell_96,0.693147,0.000000,1.098612,0.693147,0.693147,0.000000,0.693147,0.693147,0.000000,0.000000,...,1.386294,0.693147,0.693147,1.098612,1.098612,1.098612,0.000000,1.386294,1.098612,0.693147
Cell_97,0.693147,0.000000,0.693147,1.098612,0.693147,0.693147,0.000000,0.000000,0.000000,0.693147,...,0.000000,0.693147,1.098612,0.693147,0.000000,1.098612,0.693147,1.386294,0.000000,1.098612
Cell_98,1.386294,0.693147,0.693147,0.000000,0.000000,0.693147,0.693147,0.693147,0.693147,0.000000,...,0.000000,0.000000,0.693147,1.386294,0.693147,0.693147,1.098612,1.098612,0.000000,0.693147
Cell_99,0.000000,0.693147,0.693147,0.693147,1.386294,0.693147,0.693147,1.098612,0.000000,0.000000,...,0.693147,0.693147,0.000000,0.693147,1.098612,0.000000,0.000000,0.693147,0.000000,1.386294

In [43]:
adata.write('my_results.h5ad', compression="gzip")

In [ ]:
!sudo apt install tree

In [53]:
!tree

.
├── my_results.h5ad
└── sample_data
    ├── anscombe.json
    ├── california_housing_test.csv
    ├── california_housing_train.csv
    ├── mnist_test.csv
    ├── mnist_train_small.csv
    └── README.md

1 directory, 7 files

In [ ]:
!sudo apt-get install hdf5-tools

In [60]:
!h5ls 'my_results.h5ad'

X                        Group
layers                   Group
obs                      Group
obsm                     Group
obsp                     Group
uns                      Group
var                      Group
varm                     Group
varp                     Group

In [63]:
obs_meta = pd.DataFrame({
        'time_yr': np.random.choice([0, 2, 4, 8], adata.n_obs),
        'subject_id': np.random.choice(['subject 1', 'subject 2', 'subject 4', 'subject 8'], adata.n_obs),
        'instrument_type': np.random.choice(['type a', 'type b'], adata.n_obs),
        'site': np.random.choice(['site x', 'site y'], adata.n_obs),
    },
    index=adata.obs.index,    # these are the same IDs of observations as above!
)
obs_meta

         time_yr subject_id instrument_type    site
Cell_0         0  subject 1          type a  site x
Cell_1         8  subject 8          type b  site x
Cell_2         4  subject 4          type a  site y
Cell_3         8  subject 1          type a  site y
Cell_4         2  subject 8          type b  site x
...          ...        ...             ...     ...
Cell_95        0  subject 4          type a  site y
Cell_96        2  subject 4          type b  site y
Cell_97        4  subject 8          type a  site y
Cell_98        0  subject 2          type b  site y
Cell_99        2  subject 2          type a  site y

[100 rows x 4 columns]

In [65]:
adata = ad.AnnData(adata.X, obs=obs_meta, var=adata.var)
adata

AnnData object with n_obs × n_vars = 100 × 2001
    obs: 'time_yr', 'subject_id', 'instrument_type', 'site'